### ISSUE TITLE
Having trouble installing

### ISSUE THREAD

**Issue by MathiasHaudgaard** [DirtyHarryLYL/Transferable-Interactiveness-Network#10]
When I'm installing the requirements, it stops at datasets=0.0.9 with the error code 
![image](https://user-images.githubusercontent.com/10813266/59423295-28e11900-8dd2-11e9-82d9-12e2b318a894.png)

Anyone experiencing the same problem?

**Comment by HuangOwen** [comment]
Hi, @MathiasHaudgaard Which version of pip are you using? Maybe you can try to upgrade it via
`pip install --upgrade pip`
Or you can try conda/virtualenv to install these dependencies.

**Comment by MathiasHaudgaard** [comment]
My environment consists of the following packages: 
![image](https://user-images.githubusercontent.com/10813266/59427521-1f0fe380-8ddb-11e9-850d-cec792f0dca7.png)

**Comment by HuangOwen** [comment]
This might help [link](https://stackoverflow.com/questions/38163760/cant-install-datasets-package-via-pip)

**Comment by MathiasHaudgaard** [comment]
Yeah, I also found that link but I'm asking if anyone else is experiencing the same problem installing the datasets package or if it's only me.
