### ISSUE TITLE
about .pkl file for train

### ISSUE THREAD

**Issue by Pursue26** [DirtyHarryLYL/Transferable-Interactiveness-Network#11]
Hi, thanks for the great work!

I browsed your code for HICO-DET dataset, and I've seen the code for iCAN before.
I saw that you used the .pkl file in function  Train_TIN_HICO.py, and (QUESTION_1) i want to know if your Trainval_GT and Trainval_N . pkl file adds a part about pose to the. pkl file (Compared with iCAN). 
Because I saw your pickle.load function loaded '*_with_pose. pkl'('with_pose'), but (QUESTION_2) I didn't find where to download this .pkl file for train (with a pose info's .pkl file).
i.e.
''' 
Trainval_GT  = pickle.load( open( cfg.DATA_DIR + '/' + 'Trainval_GT_HICO_with_pose.pkl', "rb" ))
Trainval_N   = pickle.load( open( cfg.DATA_DIR + '/' + 'Trainval_Neg_HICO_with_pose.pkl', "rb" ) )
'''
I can't work with the Trainval_GT and Trainval_N .pkl file of iCAN because it will make an error: 
'''
  File "..\lib\ult\ult.py", line 793, in Augmented_HO_Neg_HICO_pose_pattern_version2
  Pattern_ = Get_next_sp_with_pose(Human_augmented_temp[j][1:], Object_augmented_temp[j][1:], GT[GT_count - 1][5]).reshape(1, 64, 64, 3)
IndexError: list index out of range
'''
if you add information about pose to Trainval_GT.pkl, i will another question (QUESTION_3): Trainval_GT.pkl should be grouth-truth anno, but official anno_bbox.mat file has no information about pose, and how to deal with it, please.

And, I'm not clear how to generate Trainval_Neg_HICO_with_pose.pkl files. Can you provide some relevant code or ideas&process? I will be very grateful.
thank you very much!

**Comment by HuangOwen** [comment]
Hi @Pursue26 
We have said that the codes are developed from iCAN and we use their detection while adding pose to it. In Download_data.sh we have
`python script/Download_data.py 12-ZFl2_AwRkVpRe5sqOJRJrGzBeXtWLm Data/Test_Faster_RCNN_R-50-PFN_2x_HICO_DET_with_pose.pkl
python script/Download_data.py 1y3cnbX12jwNAoSiXDLcdzn-nF_jvsaum Data/Test_Faster_RCNN_R-50-PFN_2x_VCOCO_with_pose.pkl`
In Acknowledgement part we also talked about how we generate pose estimation, please read it carefully.
