### ISSUE TITLE
script

### ISSUE THREAD

**Issue by xue2015210194** [DirtyHarryLYL/Transferable-Interactiveness-Network#12]

**Comment by xue2015210194** [comment]
When I download the dataset, I have some trouble in finding script_pick_annotations.py. Anyone who meets the same problem?

**Comment by HuangOwen** [comment]
Please check if script_pick_annotations.py is in your ROOT/Data/v-coco/ path. If not, you can go to https://github.com/s-gupta/v-coco to download it.
