### ISSUE TITLE
what is file '-Results/80000_TIN_D_noS.pkl'

### ISSUE THREAD

**Issue by desenzhou** [DirtyHarryLYL/Transferable-Interactiveness-Network#15]
Hi, I simply run the command 'python tools/Test_TIN_HICO.py --num_iteration 1700000 --model TIN_HICO' for testing, but encountered a problem that cannot find '-Results/80000_TIN_D_noS.pkl'   in HICO_Benchamrk_Binary.py, I have no idea where this file is saved and how is the format it is saved.

**Comment by desenzhou** [comment]
I found that I simply replacing '-Results/80000_TIN_D_noS.pkl'  with '-Results/1700000_TIN_HICO_0.8_0.3new_pair_selection_H2O2.pkl' is able to start the evaluation

**Comment by HuangOwen** [comment]
That's interactiveness prior model D in our paper. Sorry for that we forget to upload it. We'll upload it soon.

**Comment by HuangOwen** [comment]
We add it to our script, you can download it via
`https://drive.google.com/open?id=1sjV6e916NIPcYYqbGwhKM6Vhl7SY6WqD`
 now

**Comment by desenzhou** [comment]
Now I cannot find '-Results/60000_TIN_VCOCO_D.pkl'
