### ISSUE TITLE
Question About TIN_VCOCO.py

### ISSUE THREAD

**Issue by ASMIftekhar** [DirtyHarryLYL/Transferable-Interactiveness-Network#16]
Hey,
Thanks for the repo.In TIN_VCOCO.py, you guys introduced HO_weight(Line 77) and H_weight(Line 83). From where you got those values or is it just trial and error?

**Comment by HuangOwen** [comment]
Hi, @ASMIftekhar 
The weight aims to solve the category imbalance of different HOI and is calculated by the logarithm of samples of different categories.

**Comment by ASMIftekhar** [comment]
Thanks a lot.
