### ISSUE TITLE
Query About Low-grade Instance Suppressive Function

### ISSUE THREAD

**Issue by ASMIftekhar** [DirtyHarryLYL/Transferable-Interactiveness-Network#17]
Hey,
Thanks for the repo. In section 4.3 of the paper, you introduced LIS function. Can you point me out the location where this function is implemented in the code? I am basically curious about how to get the value of **T**, **k** and **W** in the logistic function.

**Comment by HuangOwen** [comment]
Hi @ASMIftekhar 
We use different NIS parameters for V-COCO and HICO dataset. 
For HICO, it's in HICO-DET_benchmark/Generate_HICO_detection_nis.py (line38-40 & 72)
For V-COCO, it's in tools/Vcoco_lis_nis.py (line 304)

**Comment by ASMIftekhar** [comment]
Thanks a lot.
