### ISSUE TITLE
Question about the detector and feature extractor

### ISSUE THREAD

**Issue by goolhanrry** [DirtyHarryLYL/Transferable-Interactiveness-Network#21]
Hi! Thanks for your great work!

I've read your code and noticed that int your model, you imported the detection results from Detectron in `Data/Test_Faster_RCNN_R-50-PFN_2x_HICO_DET.pkl`, which contains bbox annotations of human and objects. And used another simplified ResNet-50 (just stage1 to stage4) to extract features from the proposals cropped from the raw image according to the annotations above. Is my description true in the model? I would really appreciate it if you can correct me if I am wrong.

Many thanks for your attention! 😁

**Comment by HuangOwen** [comment]
You are right, but we're actually using Data/Test_Faster_RCNN_R-50-PFN_2x_HICO_DET_with_pose.pkl which also includes pose detection result.

**Comment by goolhanrry** [comment]
Thanks for your reply!

May I ask have you tried to use the features from stages in the detector directly, instead of extracting the features once more before entering the three streams? I'm thinking of whether it is necessary to re-extract the features again.

**Comment by HuangOwen** [comment]
We have tried that but it turned out to decrease the mAP.

**Comment by goolhanrry** [comment]
Thanks a lot!
