### ISSUE TITLE
Why not use YOLO as well as SSD as the instance detector.

### ISSUE THREAD

**Issue by BIGJUN777** [DirtyHarryLYL/Transferable-Interactiveness-Network#24]
Hello,

Thank you for your good works.

After reading some papers on the task, I realized they all leverage the Faster R-CNN as the instance detector. I am not sure the main reason for this because YOLO and SSD are also nice detectors. That really confuses me these days. Could anyone please explain this if you are aware of the reason.

Thanks.

**Comment by HuangOwen** [comment]
Hi @BIGJUN777 Thanks for your attention and sorry for the late reply
As far as I'm concerned, two-stage detectors should be significantly better than one-stage detectors on accuracy. HOI detection requires accurate bboxs of human and object, so we just use R-CNN. I think researchers use YOLO/SSD when there is a speed limit or computational resource limit.

**Comment by BIGJUN777** [comment]
Yes, maybe this is one of the reasons. But YOLO3 gained a nice detection result as well. As for R-CNN, I think it is easier to reuse the corresponding features for later HOI detection. Besides, maybe it is for a fair comparison. This question is just out of curiosity.

Thanks.
