### ISSUE TITLE
Error using Generate_detection>(parfor body) (line 19).   please

### ISSUE THREAD

**Issue by njuhuxw** [DirtyHarryLYL/Transferable-Interactiveness-Network#26]
Error using Generate_detection>(parfor body) (line 19)
Unable to read file
'/home/magus/huxw-workspace/Transferable-Interactiveness-Network/-Results/TIN_HICONIS_thres_x0.1_y0.9/detections_14.mat'.
No such file or directory.

Error in Generate_detection (line 17)
parfor obj_idx = 1 : 80

**Comment by HuangOwen** [comment]
In the benchmark test phase, we first convert .pkl file to .mat file. Please check if the .mat file are generated correctly.

**Comment by njuhuxw** [comment]
can you tell me that: this error is caused by I run the test.py directly of your pre-trained weight?

if I train ,then test, the output is right.
can you tell me the reason? please, thank you.

**Comment by HuangOwen** [comment]
I don't think this error is caused by directly running test on pre-trained weight since we and most users successfully reproduce the results. Please be sure to check the path of the weight, .pkl file and .mat file

**Comment by njuhuxw** [comment]
Thank you very much, I get it.
