### ISSUE TITLE
How should I insert my  own pose estimation results in the PLK file

### ISSUE THREAD

**Issue by YSN1011** [DirtyHarryLYL/Transferable-Interactiveness-Network#29]
Hello, may I ask how should I insert my  own pose estimation results in the PLK file

**Comment by DirtyHarryLYL** [comment]
Hi, within the pkl file, each human box is assigned with his/her pose joints, you could replace our pose with yours in the same format directly. 
If the joints number is changed, the pose map construction needs to be changed.
