### ISSUE TITLE
GT and Neg？

### ISSUE THREAD

**Issue by YSN1011** [DirtyHarryLYL/Transferable-Interactiveness-Network#30]
Hello, may I ask how the GT and Neg in the pre-training model were obtained respectively?

**Comment by HuangOwen** [comment]
Hi @YSN1011 
In training, positive examples (GT) are given by the dataset. To obtain negative examples:
1> Detect all objects in an image
2> Pair all the Human and Object that has the score higher than a threshold
3> HO pairs that are not included in the GT, are the negative examples

**Comment by YSN1011** [comment]
Thank you. Compared with iCAN, the pre-training model of this paper has more posture parts, so how can GT and Neg of posture parts be obtained by Alphapose?

**Comment by HuangOwen** [comment]
We first run Alphapose on every image of our dataset. To be noticed, Alphapose detection results contain bbox for humans. Then we match the bbox in the pose estimation results with the bbox in the data.pkl with a given IoU threshold.

**Comment by YSN1011** [comment]
And then add the selected negative sample data to the iCAN's pre-training model?

**Comment by HuangOwen** [comment]
Sure, neg samples also have bbox, we just match pose with them considering IoU.

**Comment by YSN1011** [comment]
So if I want to use the result of my attitude estimation, only one result file is generated, how should I pick out Neg?Then how should I replace the result of Alphapose?Thank you very much。

**Comment by HuangOwen** [comment]
I'm not sure if I get what you mean by "attitude estimation" and "only one result file". For how to pick out Neg, I have explained it, you should run object detection to get Human-Object pairs. To replace Alphapose you just need to compute IoU between different human bbox, if the bbox matches, you just replace it.
 
> Hi @YSN1011
> In training, positive examples (GT) are given by the dataset. To obtain negative examples:
> 1> Detect all objects in an image
> 2> Pair all the Human and Object that has the score higher than a threshold
> 3> HO pairs that are not included in the GT, are the negative examples
