### ISSUE TITLE
Test on custom images/video

### ISSUE THREAD

**Issue by aditya-droid** [DirtyHarryLYL/Transferable-Interactiveness-Network#31]
Hi,
First of all I would like to thank you for the awesome work you have done. It is quite impressive to see such great results. 

I need to run the network on some custom images and a custom video, but I am a bit confused as to whether or not this is possible with the code shipped in your repository. There's a pkl file which you import to test the VCOCO detections, but how to generate this on our custom data?

**Comment by HuangOwen** [comment]
Hi @aditya-droid Thanks for your attention

If you want to train and inference on your custom dataset, you just need to generate a pkl file with the same format as our pkl format. We currently do not support video input, but you can cut your video into frames and run detection on each frame.

For vcoco, the format is listed below:
`# Trainval_GT: Trainval_GT_VCOCO.pkl
[ # a list of annotation of all images
	[
		226162, # image_id,  pic_name = 'COCO_train2014_' + (str(image_id)).zfill(12) + '.jpg'
		[25, 14], # action_HO, positive action for action between human(agent) and object(instr,obj)
		array([154.49,  71.25, 312.81, 395.57]), # Human (x1,y1,x2,y2) (x1,y1) is upper left point, (x2,y2) is lower right point
		array([ 35.3 , 143.39, 390.89, 245.51]), # Object (x1,y1,x2,y2) (x1,y1) is upper left point, (x2,y2) is lower right point
		[25, 27, 3, 18, 14] # action_H, positive action_id, only human(agent)
	],
	# ......
]

# Trainval_N: Trainval_Neg_VCOCO.pkl
{
	226162: # image_id
	[
		[
			226162, # image_id
			array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]), # no use for train
			array([154.49,  71.25, 312.81, 395.57]), # Human bbox
			array([229.4 ,   1.34, 404.86,  59.02]), # Object bbox
			nan, # no use for train
			3, # no use for train
			array(1) # no use for train
		], 
		[226162, array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]), array([154.49,  71.25, 312.81, 395.57]), array([ 57.72,   0.55, 180.87,  63.7 ]), nan, 3, array(1)], 
		#......
    ],
    # ......
}`

**Comment by aditya-droid** [comment]
Okay, I get that this pkl file can be used for inferencing results from your model, but for that I would need to generate dictionaries of every image that I am feeding to the model and those will be: person bounding box, object bounding box for every image, right?

**Comment by HuangOwen** [comment]
You are right. You also need pose estimation result to generate this dictionary. You can use Alphapose or openpose to generate it.

**Comment by aditya-droid** [comment]
Okay, thanks for the help. I get it now.
