### ISSUE TITLE
Changed the feature extraction resnet50 to resnet101, but AP decreased?

### ISSUE THREAD

**Issue by YSN1011** [DirtyHarryLYL/Transferable-Interactiveness-Network#32]
I changed the feature extraction resnet50 to resnet101. Why did the depth increase but the AP decrease?

**Comment by HuangOwen** [comment]
Hi @YSN1011 
Change to a deeper network does not guarantee better accuracy. In this scenario, the feature extracted by ResNet50 is more suitable for HOI detection than ResNet101.
