### ISSUE TITLE
About from_previous_ckpt and from_best_trained_model 

### ISSUE THREAD

**Issue by SherlockHolmes221** [DirtyHarryLYL/Transferable-Interactiveness-Network#33]
Thanks for your job! 
Why fix some parameters when loading model [from_previous_ckpt and from_best_trained_model](https://github.com/DirtyHarryLYL/Transferable-Interactiveness-Network/blob/master/lib/models/train_Solver_HICO_pose_pattern_inD_more_positive_coslr.py)

**Comment by HuangOwen** [comment]
Hi @SherlockHolmes221 Thanks for your attention

We fix some parameters because the network structure of the previous best model is slightly different from the final model.

**Comment by SherlockHolmes221** [comment]
Thanks a lot!
