### ISSUE TITLE
About 60000_TIN_VCOCO_D.pkl

### ISSUE THREAD

**Issue by SherlockHolmes221** [DirtyHarryLYL/Transferable-Interactiveness-Network#35]
File "tools/vcoco_lis_nis.py", line 184, in generate_pkl
    score_binary_d = np.array(dic_d['binary_score'])
KeyError: 'binary_score'

the dic_d is 60000_TIN_VCOCO_D.pkl, and I have download it from https://docs.google.com/uc?export=download&id=1sJipmoZ-5u0ymm8diqYd5Yqk2A-QQBXN

**Comment by DirtyHarryLYL** [comment]
Yeah, you need to download the predictions of the interactiveness model, then use them as the reference in NIS function.
Any problems?

**Comment by SherlockHolmes221** [comment]
Thanks for your reply!
One more question:
Should I replace the  '60000_TIN_VCOCO_D.pkl'  and '80000_TIN_D_noS.pkl' when testing my model in hico and vcoco dataset cause the best binary_score in these two file(used in NIS) is no long match the index of my trained model's predicted hoi pairs? Or I should keep them?

**Comment by DirtyHarryLYL** [comment]
Yeah, if you have replaced the human-object pairs, like the boxes, then the interactiveness binary scores are no longer suitable. 
You could retrain the interactiveness model and the HOI model on your own pairs.
Then after obtaining your own best interactiveness scores, you may use them to filtering the non-interactive pairs.

**Comment by SherlockHolmes221** [comment]
Got it! Thanks for your reply! 
Then I want to ask where  I can download your predictions of the interactiveness model of vcoco？

**Comment by DirtyHarryLYL** [comment]
You could use:
python script/Download_data.py 1sjV6e916NIPcYYqbGwhKM6Vhl7SY6WqD -Results/80000_TIN_D_noS.pkl
python script/Download_data.py 1sJipmoZ-5u0ymm8diqYd5Yqk2A-QQBXN -Results/60000_TIN_VCOCO_D.pkl
to download the interactiveness scores for HICO-DET and V-COCO, or you may just directly run the script: script/download_dataset.sh. It will get everything done.

**Comment by SherlockHolmes221** [comment]
I have download the 60000_TIN_VCOCO_D.pkl following the script, but when I open the pickle file, I didn't find the binary score for NIS, and in fact I found the 60000_TIN_VCOCO_D.pkl is a file after NIS.
The picture below shows it, and where I should find the  binary score?

![5574fafe437ab5833c0b1cf18e8e5e0](https://user-images.githubusercontent.com/28208801/70140615-16d09b00-16d0-11ea-9b65-71f3d1be70cb.png)

**Comment by DirtyHarryLYL** [comment]
![image](https://user-images.githubusercontent.com/13531138/70152778-c87bc600-16e8-11ea-90a8-b169fcfe59e4.png)

**Comment by SherlockHolmes221** [comment]
Sorry for my carelessness, thanks a for your patience. I will close the issue.

**Comment by wanna-fly** [comment]
> File "tools/vcoco_lis_nis.py", line 184, in generate_pkl
> score_binary_d = np.array(dic_d['binary_score'])
> KeyError: 'binary_score'
> 
> the dic_d is 60000_TIN_VCOCO_D.pkl, and I have download it from https://docs.google.com/uc?export=download&id=1sJipmoZ-5u0ymm8diqYd5Yqk2A-QQBXN

I have downloaded the prediction file but still got a KeyError when running `Test_TIN_VCOCO.py`. Could you please tell me how do you solve this problem?

**Comment by Foruck** [comment]
> > File "tools/vcoco_lis_nis.py", line 184, in generate_pkl
> > score_binary_d = np.array(dic_d['binary_score'])
> > KeyError: 'binary_score'
> > the dic_d is 60000_TIN_VCOCO_D.pkl, and I have download it from https://docs.google.com/uc?export=download&id=1sJipmoZ-5u0ymm8diqYd5Yqk2A-QQBXN
> 
> I have downloaded the prediction file but still got a KeyError when running `Test_TIN_VCOCO.py`. Could you please tell me how do you solve this problem?

Thanks for using our code! Would you mind providing more detailed error information?

**Comment by wanna-fly** [comment]
Thanks for your reply, especially in this Dragon Boat Festival holiday! Finally I fixed this error by changing the key from `'binary_score'` to `b'binary_score'`, and now it works fine. By the way , How do you guys get the `HO_weight` and `H_weight`  appeared in the `TIN_VCOCO.py`?

**Comment by Foruck** [comment]
Please refer to #36 for detailed description. The weight generation strategies for HICO-DET and V-COCO are the same.

**Comment by Foruck** [comment]
> Thanks for your reply, especially in this Dragon Boat Festival holiday! Finally I fixed this error by changing the key from `'binary_score'` to `b'binary_score'`, and now it works fine. By the way , How do you guys get the `HO_weight` and `H_weight` appeared in the `TIN_VCOCO.py`?

Please refer to #36 for detailed description. The weight generation strategies for HICO-DET and V-COCO are the same.

**Comment by wanna-fly** [comment]
Got it! Many thanks for helping:)
