### ISSUE TITLE
please help me ! I can not find the files.

### ISSUE THREAD

**Issue by njuhuxw** [DirtyHarryLYL/Transferable-Interactiveness-Network#40]
Hi, 
Thanks to reading this mail.
Please help me ! 
I can not find the files of that 'vcoco_test.json', ' instances_vcoco_all_2014.json' and ' v-coco/data/splits/vcoco_test.ids'.

Can you tell me how to download the files or give me them by mail "hu_xinwen@smail.nju.edu.cn".
Thanks very much.

**Comment by DirtyHarryLYL** [comment]
To download dataset, setup evaluation and API:
```
chmod +x ./script/Dataset_download.sh 
./script/Dataset_download.sh
```
Detailed information can be found in .sh file or here: https://github.com/s-gupta/v-coco.

**Comment by njuhuxw** [comment]
thanks very much.
