### ISSUE TITLE
60000_TIN_VCOCO_D.pkl

### ISSUE THREAD

**Issue by LawrenceChengJiaxiang** [DirtyHarryLYL/Transferable-Interactiveness-Network#42]
Hello! Thank you very much for your open-source work!
I would like to know how to get the ..._TIN_VCOCO**_D.pkl.** It seems I can only get the ...naked.pkl with data format not available for direct visualization.
Many thanks for your help in advance!

**Comment by Foruck** [comment]
You can download it from [https://docs.google.com/uc?export=download&id=1sJipmoZ-5u0ymm8diqYd5Yqk2A-QQBXN](https://docs.google.com/uc?export=download&id=1sJipmoZ-5u0ymm8diqYd5Yqk2A-QQBXN).
