### ISSUE TITLE
About the batchsize and epoch

### ISSUE THREAD

**Issue by YSN1011** [DirtyHarryLYL/Transferable-Interactiveness-Network#43]
Hello, thank you for your work.Your code only has places for iteration, but not for batchsize and epoch.So how are these two parameters set?
Thank you very much.

**Comment by Foruck** [comment]
For each iteration, we fed one image to the model, along with 15 augmented GT pairs and at most 60 Neg pairs (if there were enough).
We didn't use epoch to measure the training process.

**Comment by YSN1011** [comment]
But in the code, the shape of fc7_H is (16, 1024)，and the sp is (46, 1024).So I want to ask what does 16 and 46 mean?

**Comment by Foruck** [comment]
The shapes of fc7_H and some other features varies during the whole training process, depending on the number of pairs fed along with the image. In this example, 16 and 46 means this image is fed to the model along with 16 GT pairs and 30 Neg pairs (16 + 30 = 46).

**Comment by Foruck** [comment]
Also, the shapes of fc7_H and sp mentioned ((16, 1024) and(46, 1024)) were probably wrong, since fc7_H should have a size of (?, 2048) and sp should have a size of (?, 5408).

**Comment by YSN1011** [comment]
Thank you for your answer.I made a mistake because I changed the dimensions of both to 1024.But (?, 2048), (?,5408 )is the shape of the tensor that I'm going to put out directly, and then I'm going to put it into numpy form, and the outputs are (16,2048) and (46,5408).

**Comment by YSN1011** [comment]
GT pair is given directly by the label, right? So how does Neg pair come about?

**Comment by Foruck** [comment]
Yep. And if you output the shape in another iteration, you will find their shapes vary.

**Comment by Foruck** [comment]
> GT pair is given directly by the label, right? So how does Neg pair come about?

You can refer to #25 and #30 for this question.

**Comment by YSN1011** [comment]
Thank you very much. Your answer helped me a lot
