### ISSUE TITLE
where is res50_faster_rcnn?

### ISSUE THREAD

**Issue by mansooreh1368** [DirtyHarryLYL/Transferable-Interactiveness-Network#44]
when run "python tools/Train_TIN_HICO.py --num_iteration 2000000 --model TIN_HICO_test"
give this error "tensorflow.python.framework.errors_impl.NotFoundError: FindFirstFile failed for: E:/Transferable-Interactiveness-Network-master/Transferable-Interactiveness-Network-master/Weights/res50_faster_rcnn : The system cannot find the path specified."

**Comment by mansooreh1368** [comment]
In folder Weights does not exist res50_faster_rcnn
what do I do?

**Comment by YSN1011** [comment]
You need to download the following three files and put them in the folder Weights/res50_faster_rcnn：
res50_faster_rcnn_iter_1190000.ckpt.meta
res50_faster_rcnn_iter_1190000.ckpt.index
res50_faster_rcnn_iter_1190000.ckpt.data-00000-of-00001
These are the resnet50's pre-training models

**Comment by Foruck** [comment]
You could find how to download the weight files in [this link](https://github.com/vt-vl-lab/iCAN/blob/master/misc/download_dataset.sh).

**Comment by mansooreh1368** [comment]
Hello
thanks for your answer
when I run test phase "python tools/Test_TIN_HICO.py --num_iteration 1700000 --model TIN_HICO"
give this error :ValueError: The passed save_path is not a valid checkpoint: F:\Transferable-Interactiveness-Network-master\Transferable-Interactiveness-Network-master/Weights/TIN_HICO/HOI_iter_17.ckpt

In the folder Weights/TIN_HICO is the following files:
res50_faster_rcnn_iter_1190000.ckpt.meta
res50_faster_rcnn_iter_1190000.ckpt.index
res50_faster_rcnn_iter_1190000.ckpt.data-00000-of-00001

**Comment by YSN1011** [comment]
There should be two folders under your Weights folder, TIN_VCOCO_default for the trained model and res50_faster_rcnn for the resnet model

**Comment by mansooreh1368** [comment]
I want to run this program on  HICO_DET dataset only and don't download VCOCO dataset.
The training phase run without any error . but in testing phase the program search about" HOI_iter_17.ckpt " and it isn't in my folders.
what is HOI_iter_17.ckpt and where is?
In training phase create a folder with TIN_HICO_test folder in Weights folder which have following files:
HOI_iter_10.ckpt.meta
HOI_iter_10.ckpt.index
HOI_iter_10.ckpt.data-00000-of-00001
checkpoint

**Comment by Foruck** [comment]
The checkpoint name 'HOI_iter_17.ckpt' you mentioned is probably a mistake of 'HOI_iter_1700000.ckpt'. You could download the weight file by running 
`python script/Download_data.py 1f_w7HQxTfXGxOPrkriu7jTyCTC-KPEH3 Weights/TIN_HICO.zip`. The downloaded weights will be saved in `./Weights/TIN_HICO/`.
Or if you are training your own model, notice the checkpoint is saved every 100000 iterations (HOI_iter_10.ckpt is saved for sanity check). You could choose which checkpoint to test by changing the `num_iteration` flag.

**Comment by DirtyHarryLYL** [comment]
Solved
