### ISSUE TITLE
Zero values for mAP

### ISSUE THREAD

**Issue by mansooreh1368** [DirtyHarryLYL/Transferable-Interactiveness-Network#45]
Hello
When I fix errors and run "python tools/Test_TIN_HICO.py --num_iteration 1700000 --model TIN_HICO
" it crate a notepad file as name of eval_result.txt which have following values:
setting:     def
exp_name:    rcnn_caffenet_ho_pconv_ip1_s
score_blob:  n/a

  mAP / mRec (full):      0.0000 / 0.0000

  mAP / mRec (rare):      0.0000 / 0.0000
  mAP / mRec (non-rare):  0.0000 / 0.0000

setting:     ko
exp_name:    rcnn_caffenet_ho_pconv_ip1_s
score_blob:  n/a

  mAP / mRec (full):      0.0000 / 0.0000

  mAP / mRec (rare):      0.0000 / 0.0000
  mAP / mRec (non-rare):  0.0000 / 0.0000

Why return all values to zero?

**Comment by Foruck** [comment]
More information to reproduce the result is needed for us to resolve it. 

And for general check, were the weight file and data file right?
