### ISSUE TITLE
excuse me, how to get self.HO_weight ? thank you

### ISSUE THREAD

**Issue by whyang78** [DirtyHarryLYL/Transferable-Interactiveness-Network#46]
self.HO_weight   = np.array([
                9.192927, 9.778443, 10.338059, 9.164914, 9.075144, 10.045923, 8.714437, 8.59822, 12.977117, 6.2745423, 
                11.227917, 6.765012, 9.436157, 9.56762, 11.0675745, 11.530198, 9.609821, 9.897503, 6.664475, 6.811699, 
                6.644726, 9.170454, 13.670264, 3.903943, 10.556748, 8.814335, 9.519224, 12.753973, 11.590822, 8.278912, 
                5.5245695, 9.7286825, 8.997436, 10.699849, 9.601237, 11.965516, 9.192927, 10.220277, 6.056692, 7.734048, 
                8.42324, 6.586457, 6.969533, 10.579222, 13.670264,.......]

**Comment by DirtyHarryLYL** [comment]
a*lg[1/(k/N)], k is the sample number of this HOI class, N is the number of all samples, thus k/N is the "occurrence" or "probability". High-frequency classes need fewer weights. a is the term weight.

**Comment by whyang78** [comment]
thank you ! can you share this code? i don't know how to get term weight.

**Comment by whyang78** [comment]
> a*lg[1/(k/N)], k is the sample number of this HOI class, N is the number of all samples, thus k/N is the "occurrence" or "probability". High-frequency classes need fewer weights. a is the term weight.

excuse me, how to get term weight ? thank you!
