### ISSUE TITLE
How to select correct HOI from multiple predictions  during test time.

### ISSUE THREAD

**Issue by feedforward** [DirtyHarryLYL/Transferable-Interactiveness-Network#48]
Hi, 
Thank you for making your code available. I've one question.

During test time test_net function in lib/models/test_HICO_pose_pattern_all_wise_pair.py generates multiple hoi detections for each image. Only a few of them are correct predictions, while others are not. But all of them have very high prediction scores. How are you selecting the correct predictions while ignoring the wrong predictions?

This is the information from code that is curated into the pkl file.

                temp.append(Human_out[2])           # Human box
                temp.append(Object[2])              # Object box
                temp.append(Object[4])              # Object class
                temp.append(prediction_HO[0])       # Score (600)
                temp.append(Human_out[5])           # Human score
                temp.append(Object[5])              # Object score
                temp.append(prediction_binary[0])   # binary score

looking to visualize the hoi detections. Any suggestions are really appreciated.

**Comment by DirtyHarryLYL** [comment]
Hi,
in fact, the ''right" prediction is decided by the thresholds or rank. And different metrics may have different rules. 
For example, for the object apple, action hold, I can set the threshold as 0.85. 
Then all the predictions with action score higher than 0.85 and the box IoU higher than 0.5 (h and o both) are "right". 
Or I can also rank all the prediction of HOI "hold apple" of *all testing images* and choose the top-k predictions as the "right" predictions (boxes should be accurate too).
The detailed metric about how cal the mAP could be found in the evaluation files, they may help you too.
Or you can also only visualize the "true positive" found by the evaluation code as the "right" predictions.
