### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by mahsa1363** [DirtyHarryLYL/Transferable-Interactiveness-Network#49]
hi
thanks for your code
I have some questions
1-Is there in one image just one HOI class? when I run demo_visualize, for each image, several human and several objects may be identified but their hoi class is the same.
I dont understand about dataset, please help me
2-please explain about Trainval_GT_HICO.pkl file
thanks

**Comment by DirtyHarryLYL** [comment]
Hi,
1-one image may contain multiple HOIs, i.e., human-object pairs. More details could be found in the HICO-DET dataset and paper.
2-The details of Trainval_GT_HICO.pkl could also be found on iCAN website. We use their training boxes, the only difference is we add the pose in the Trainval_GT_HICO_with_pose.pkl.
