### ISSUE TITLE
About human pose feats and HICO-Det Dataset Annotation

### ISSUE THREAD

**Issue by YueLiao** [DirtyHarryLYL/Transferable-Interactiveness-Network#5]
Good job!
1.Do you use the alpha-pose result trained on MPII or COCO dataset?
2.I would like to know if you filter keypoints  the score of which blow the threshold(maybe 0.05 in coco). If done,  how to construct the human skeleton if missing some keypoints.

**Comment by DirtyHarryLYL** [comment]
1. We used the pre-trained Alphapose model (on COCO).
2. Yeah, we used the filtering. We have tried different filtering thresholds, e.g., 0.05, 0.1. The performances are similar. If some points are missing or discarded, the corresponding skeleton edges/lines will also be discarded. 
![image](https://user-images.githubusercontent.com/13531138/56375975-65145500-6239-11e9-875b-53676d77107e.png)

**Comment by YueLiao** [comment]
Thanks for the reply. I got it.
Another question about hico-det detection annotation:
On HICO-DET dataset, the same object may be annotated by several bouding-boxes which have high IOU with each other.  I wonder if you have done something for it.

**Comment by DirtyHarryLYL** [comment]
Yes. If our setting, two human or object boxes with Iou>0.7 will be seen as the same person or object. We fuse the boxes which have high IoU，and merge their labels.

**Comment by YueLiao** [comment]
I got you. Thanks a lot. It's very helpful for me.
