### ISSUE TITLE
Always 1 prediction for the interactivity class?

### ISSUE THREAD

**Issue by kilickaya** [DirtyHarryLYL/Transferable-Interactiveness-Network#50]
Hi, 

When I feed-forward the images with the provided human-object detections, the interactivity network always outputs a confidence of 1, and 0 to no-interactivity. 

I use the provided network weights with the evaluation code (Test_TIN_HICO), and did not do any training myself. 

Is this expected? Or does it mean a degenerate solution? 

Thank you.

**Comment by Foruck** [comment]
This is probably caused by over-fitting. The interactivity network would fit in less than 100k iterations. May be you can try to reduce the number of iteration.

**Comment by kilickaya** [comment]
I used the pre-trained weights provided in this repo python script/Download_data.py 1f_w7HQxTfXGxOPrkriu7jTyCTC-KPEH3 Weights/TIN_HICO.zip

How many iterations this weights were trained with? So that I can use a lower number of iterations.

**Comment by Foruck** [comment]
These weights were trained with 1700k iterations.
