### ISSUE TITLE
I can't download PreTrained weights from GoogleDrive!

### ISSUE THREAD

**Issue by Juzz4vijay** [DirtyHarryLYL/Transferable-Interactiveness-Network#51]
Hi, 
Thanks for your wonderful contribution.

I'm using Google Colab..

I've used this command.

!python ./script/Download_data.py 1f_w7HQxTfXGxOPrkriu7jTyCTC-KPEH3 Weights/TIN_HICO.zip
!python ./script/Download_data.py 1iU9dN9rLtekcHX2MT_zU_df3Yf0paL9s/Weights/TIN_VCOCO.zip

i got this error!

Traceback (most recent call last):

  File "./script/Download_data.py", line 52, in <module>
    download_file_from_google_drive(file_id, destination)
  File "./script/Download_data.py", line 40, in download_file_from_google_drive
    save_response_content(response, destination)
  File "./script/Download_data.py", line 24, in save_response_content
    with open(destination, "wb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'Weights/TIN_HICO.zip'
Traceback (most recent call last):
  File "./script/Download_data.py", line 52, in <module>
    download_file_from_google_drive(file_id, destination)
  File "./script/Download_data.py", line 40, in download_file_from_google_drive
    save_response_content(response, destination)
  File "./script/Download_data.py", line 24, in save_response_content
    with open(destination, "wb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'Weights/TIN_VCOCO.zip'

Thanks in advance.

**Comment by DirtyHarryLYL** [comment]
Hi, 
I have tried the link and they are all alive. Maybe you could try to create the folder "Weights", then run the script. Or you could try to download the files using:
https://drive.google.com/open?id=1f_w7HQxTfXGxOPrkriu7jTyCTC-KPEH3
https://drive.google.com/open?id=1iU9dN9rLtekcHX2MT_zU_df3Yf0paL9s

**Comment by DirtyHarryLYL** [comment]
BTW
"1iU9dN9rLtekcHX2MT_zU_df3Yf0paL9s/Weights/TIN_VCOCO.zip" is "1iU9dN9rLtekcHX2MT_zU_df3Yf0paL9s /Weights/TIN_VCOCO.zip"

**Comment by Juzz4vijay** [comment]
Thanks DirtyHarryLYL!

I forgot to create Weights folder.

now, above code is working.
