### ISSUE TITLE
about test the model，mAP value is too low

### ISSUE THREAD

**Issue by HalKarim** [DirtyHarryLYL/Transferable-Interactiveness-Network#52]
hi，i used ur pre-trained weight  ，and run the scripts
python tools/Test_TIN_HICO.py --num_iteration 1700000 --model TIN_HICO
but the mAP is lower then ur mAP value，and i didn't change anything，
this is what i get:
setting:     def
exp_name:    rcnn_caffenet_ho_pconv_ip1_s
score_blob:  n/a
  mAP / mRec (full):      0.0642 / 0.1615
  mAP / mRec (rare):      0.0493 / 0.1433
  mAP / mRec (non-rare):  0.0686 / 0.1669
setting:     ko
exp_name:    rcnn_caffenet_ho_pconv_ip1_s
score_blob:  n/a
  mAP / mRec (full):      0.0745 / 0.1615
  mAP / mRec (rare):      0.0542 / 0.1433
  mAP / mRec (non-rare):  0.0805 / 0.1669
so where i did wrong.

**Comment by Foruck** [comment]
Sorry for the late reply!
Did you download the weight by `python script/Download_data.py 1f_w7HQxTfXGxOPrkriu7jTyCTC-KPEH3 Weights/TIN_HICO.zip`? Also was the environment the same as ours?
And more detailed information is welcome, which could help a lot.
