### ISSUE TITLE
The shape of pool5_O in early and late fusion

### ISSUE THREAD

**Issue by YSN1011** [DirtyHarryLYL/Transferable-Interactiveness-Network#54]
Hello, and thank you for your job well done.
I have a problem with the code in this article.In late fusion, the pool5_O shape is (46,7,7,1024).In early fusion, pool5_O was in the shape of (16,7,7,1024).I have the following questions: 
1. Pool5_O is the same production code in both merges, so am I missing something?Why are the sample sizes inconsistent?
2. Why are the sample sizes selected differently in the two different fusion methods?
I hope we can get a solution.
Thank you very much.

**Comment by Foruck** [comment]
Could you please specify what you referred to as 'early fusion' and 'late fusion'? 
And the mentioned size infonsistency might be the result of Line 405 in [lib/networks/TIN_HICO.py](lib/networks/TIN_HICO.py), where only the first `self.H_num` object bboxes are used for ROI pooling.
