### ISSUE TITLE
 self.spatial     = tf.placeholder(tf.float32, shape=[None, 64, 64, 3], name = 'sp')

### ISSUE THREAD

**Issue by YSN1011** [DirtyHarryLYL/Transferable-Interactiveness-Network#56]
Hello, please bother you. I have a small question for you. About self.spatial = tf.placeholder(tf.float32, shape=[None, 64, 64, 3], name ='sp') in your code. You changed the 2 in the code of this paper of ICAN to 3. I would like to ask what is the reason for this change? Thank you.

**Comment by Foruck** [comment]
The first two channels of self.spatial in TIN is the same as that in iCAN. The third channel added is pose map, as shown in Fig. 4 in the paper.

**Comment by YSN1011** [comment]
Hello, I tried to follow your method and also changed the 2 channel in ICAN to 3 channel, but the following error occurred in the test.I would like to ask you, did I make a mistake during training or did I need to change the code during testing?thank you！

Pre-trained weights loaded.
2020-07-09 23:16:43.136085: W tensorflow/core/framework/op_kernel.cc:1152] Invalid argument: You must feed a value for placeholder tensor 'sp' with dtype float
         [[Node: sp = Placeholder[dtype=DT_FLOAT, shape=[], _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

**Comment by Foruck** [comment]
Did you make sure that in the feed_dict, blobs['sp'] has size of [n, 64, 64, 3] when you change the two channel in iCAN to 3 channel?

**Comment by YSN1011** [comment]
Thank you for your answer.I've changed that, sp is the third pathway, and I've added the first to the body posture estimate.So I made a mistake here, right?

**Comment by YSN1011** [comment]
About feed_dict, I modified it in test_VCOCO. Is that right?Blobs [' sp] = Get_next_sp_with_pose (Human_out [2], the Object [2], Human_out [6]), reshape (1, 64, 64, 3)

**Comment by Foruck** [comment]
If you are using checkpoint from iCAN and trying to change the channel of sp from 2 to 3, retraining of iCAN is required, since the original iCAN weight doesn't match the changed channel. If I misunderstood please point out.
Or you could check https://github.com/DirtyHarryLYL/Transferable-Interactiveness-Network/blob/b29d702d8b59a419c4337c956e9d4bd3efd1b735/lib/networks/TIN_HICO.py#L186, where iCAN weight could be used without retraining since only the first two channel is used for the pathway involving iCAN weight.

**Comment by YSN1011** [comment]
Thank you for your answer. Well, I'm trying to fuse the characteristics of the gesture estimation with the human pathway and the interaction pathway.And I've retrained.But there was an error in the test.So I think I made a mistake increasing the number of channels, but I didn't know what to do with it.

**Comment by Foruck** [comment]
Noticing your error message, probably the mistake lies in the data type? Since it didn't mention data type instead of data shape.

**Comment by YSN1011** [comment]
You may be correct, but I made the modification with reference to your TIN paper, and I am not clear where to modify this data type.
