### ISSUE TITLE
problem in installing

### ISSUE THREAD

**Issue by abdulbasit0369** [DirtyHarryLYL/Transferable-Interactiveness-Network#58]
Hi. Thankyou for your opensource code, and wonderfull work.
 i am having problem in isntalling this repo on colab
pip is not able to find model==0.6.0.
can you guide me how to get around this or is there a type in library name.
I shall be very thankful for your help
![asf](https://user-images.githubusercontent.com/56121700/93575067-9c4cdf80-f9b2-11ea-8e6b-9b3cf415f8b8.PNG)

**Comment by Foruck** [comment]
Thanks for using! This could be a redundant requirement. You could try running the code without this library, and if this works, we will remove this requirement.

**Comment by abdulbasit0369** [comment]
Hi, Sorry for the late response. I was able to run the test without above mentioned requirement. So you can remove it.
But I noticed that it is taking too long to run on google colab. So can you provide detection results of Transferable-Interactiveness-Network on HICO-DET Dataset. That will be extremely helpful. Thankyou.

**Comment by Foruck** [comment]
You could download it from [this link](https://drive.google.com/file/d/1OgQpVNS1uIpphLJPJJSYM7YDqey3NrWD/view?usp=sharing).

**Comment by abdulbasit0369** [comment]
Thank you for your help. I am closing the issue.
