### ISSUE TITLE
> 50+ mAP？wow，that is so high. No idea, maybe something went wrong, or it is the benefit of better object detections. Maybe you can convert the ican's detections to your format, and use the same model to verify the 10+% difference.

### ISSUE THREAD

**Issue by ZHUXUHAN** [DirtyHarryLYL/Transferable-Interactiveness-Network#6]
> 50+ mAP？wow，that is so high. No idea, maybe something went wrong, or it is the benefit of better object detections. Maybe you can convert the ican's detections to your format, and use the same model to verify the 10+% difference.

 I just made wrong about the evading code,i rewrites it by accuracy method,i then eval it on the val data, it can up to 43 on aprole,, i just read some papers, it's different from each other, do you eval on the val data or on the test data?

_Originally posted by @ZHUXUHAN in https://github.com/DirtyHarryLYL/Transferable-Interactiveness-Network/issues/3#issuecomment-486056774_

**Comment by DirtyHarryLYL** [comment]
We evaluate on the V-COCO test set.
