### ISSUE TITLE
V-COCO training results is bad

### ISSUE THREAD

**Issue by madoka109** [DirtyHarryLYL/Transferable-Interactiveness-Network#66]
I directly train V-COCO using weight = cfg.ROOT_DIR + '/Weights/res50_faster_rcnn/res50_faster_rcnn_iter_1190000.ckpt', but the MAP is too low. Should I train from iCAN init weight? In the code , weight = cfg.ROOT_DIR + '/Weights/iCAN_ResNet50_VCOCO_D_more_positive_15-30/HOI_iter_10000.ckpt' , how to get this file?

**Comment by madoka109** [comment]
And in the paper, there are ten parts features, but I can't find this part in the code, where are them?

**Comment by DirtyHarryLYL** [comment]
The iCAN weight is here: https://github.com/vt-vl-lab/iCAN/blob/master/misc/download_detection_results.sh.
If training from the scratch, patient tuning is needed and takes a long time.

The body part interactiveness is proposed in the PAMI version. We plan to release the new version this summer, considering lots of working burdens recently. We have first released the data split for PaStaNet-HOI.
