### ISSUE TITLE
the code for ten part boxes

### ISSUE THREAD

**Issue by WXLL579** [DirtyHarryLYL/Transferable-Interactiveness-Network#71]
thanks for your excellent work. In your code, I did not find which part is about extracting or using the ten part boxes, could you tell me ?

**Comment by DirtyHarryLYL** [comment]
Now the PAMI version using body parts is updating here (a branch): 
https://github.com/DirtyHarryLYL/Transferable-Interactiveness-Network/tree/TIN-PAMI.
