### ISSUE TITLE
where to find or download the file res50_faster_rcnn

### ISSUE THREAD

**Issue by blueballoonboom** [DirtyHarryLYL/Transferable-Interactiveness-Network#75]
excuse me,  where to find or download the file res50_faster_rcnn
tensorflow.python.framework.errors_impl.NotFoundError: /mnt/8T/glf/video_grouping/TIN/Transferable-Interactiveness-Network/Weights/res50_faster_rcnn; No such file or directory

**Comment by DirtyHarryLYL** [comment]
#44

**Comment by blueballoonboom** [comment]
Thank you!
