### ISSUE TITLE
How to use code to infer in my own data set? My own data set is not labeled, just want to see the actual application effect of HOI algorithm

### ISSUE THREAD

**Issue by ahong007007** [DirtyHarryLYL/Transferable-Interactiveness-Network#79]
How to use code to infer in your own data set? My own data set is not labeled, just want to see the actual application effect of HOI algorithm.

thank you very much!

**Comment by DirtyHarryLYL** [comment]
In TIN, if you want to infer the data out of HICO-DET and VCOCO, the human and object box detections and human pose estimations should be prepared first. Then, one image paired with its corresponding detected human, object boxes, human keypoints can be fed into the TIN to infer the HOIs.

In code, all the above things are zipped into a pkl file:
https://github.com/DirtyHarryLYL/Transferable-Interactiveness-Network/blob/e460dd03761b604184d7f0f7d3f13bbba477ee5c/tools/Test_TIN_HICO.py#L48.

If you do not need the object all the time, you could also consider a simpler tool of HAKE:
https://github.com/DirtyHarryLYL/HAKE-Action-Torch/tree/Activity2Vec, which contains the human detector and pose estimator and just needs the images/videos as inputs.
