### ISSUE TITLE
Question about final HOI classification scores

### ISSUE THREAD

**Issue by Dalanke** [DirtyHarryLYL/Transferable-Interactiveness-Network#86]
Thanks for sharing the code!

As the paper mentioned, the final HOI score should be obtained by
<img width="320" alt="Screen Shot 2022-05-25 at 20 07 18" src="https://user-images.githubusercontent.com/25289727/170258282-98c95adb-ec62-4b7a-af84-fe13054cc862.png">
Here we multiply interactiveness scores from P by the output of C.
I checked the code for HICO-DET dataset and tried to find the code doing this operation, but I only got `Generate_HICO_detection_nis.py (line72)`:
```Python
score_old = element[3][begin - 1 + i] * getSigmoid(10,1.4,0,element[4]) * getSigmoid(10,1.4,0,element[5])
```    
This line seems like applying the `LIS` mentioned in the paper
Could you kindly point out related code? Thanks!

**Comment by enlighten0707** [comment]
Please see ```Generate_HICO_detection_nis.py (line115)```:
```python
if (d_score_noi > thres_no_inter) and (d_score < thres_inter) and not(int(key) in all_remaining):
```
Here only pairs with an interactiveness score above the threshold are selected, which implements Eq. 6.

**Comment by Dalanke** [comment]
> Please see `Generate_HICO_detection_nis.py (line115)`:
> 
> ```python
> if (d_score_noi > thres_no_inter) and (d_score < thres_inter) and not(int(key) in all_remaining):
> ```
> 
> Here only pairs with an interactiveness score above the threshold are selected, which implements Eq. 6.

Thanks for your reply! 
To my understanding, it seems like Eq.6 also multiply the interactiveness scores by the classification score, am I correct? Or it just means we apply the filter to void the pairs below the threshold?

**Comment by enlighten0707** [comment]
For the code in this repo, only the filter is applied for NIS.  
It may differ a little from the description in the paper, while the basic idea is kept the same.

**Comment by Dalanke** [comment]
Thanks, I got the idea!
