### ISSUE TITLE
Issue Downloading Pretrained Weight Files 

### ISSUE THREAD

**Issue by sunjeet-radiusai** [DirtyHarryLYL/Transferable-Interactiveness-Network#92]
Downloading the weights using the command **'python script/Download_data.py 1f_w7HQxTfXGxOPrkriu7jTyCTC-KPEH3 Weights/TIN_HICO.zip**' is downloading an HTML file and not a .zip file.

**Comment by ZhongKai-07** [comment]
I meet this problem too. when i use command 'python script/Download_data.py 1zEJqQcq2KF5QC8D2TIFAo0zog0PH2LF- Data/Trainval_Neg_VCOCO_with_pose.pkl', it return a HTML file but not a .pkl  file, maybe the link is wrong?

**Comment by DirtyHarryLYL** [comment]
Maybe the google drive links are dead. We will try to update the links.

**Comment by DirtyHarryLYL** [comment]
The links are updated, please try the new ones.
